apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nadav-is
  namespace: infra-system
spec:
  secretName: nadav-is-tls
  issuerRef:
    name: letsencrypt-staging
  dnsNames:
  - '*.nadav.is'
