apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: infra-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: softly redacted 

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    solvers:
    - selector:
        dnsNames:
        - nadav.is
      dns01:
        cloudflare:
          email: softly redacted
          # !! Remember to create a k8s secret before
          # kubectl create secret generic cloudflare-api-key-secret
          apiKeySecretRef:
            name: cloudflare-token
            key: token
