apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: infra-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  data:
  - secretKey: token
    remoteRef:
      key: cloudflare-token
      property: password
