apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  data:
  - secretKey: EMAIL
    remoteRef:
      key: contact-info
      property: email
  - secretKey: SECRET_DOMAIN
    remoteRef:
      key: domain
      property: text
  - secretKey: K8S_DNS_IP
    remoteRef:
      key: k8s-dns-ip
      property: text
  - secretKey: ONO_IP
    remoteRef:
      key: vuazutmfxi643hfjccx73hsqny
      property: text
