apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfs-subdir
  namespace: flux-system
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs-subdir
  namespace: infra-system
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner # the actual name of the chart
      version: 4.x
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir # the name of the HelmRepository
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: nfs-subdir
  valuesFrom:
  - kind: ConfigMap
    name: nfs-subdir-values
    valuesKey: values.yaml
