setup host: 
  just set-token {{host}}
  just bootstrap 
  just sops

set-token host:
  ssh {{host}} "sudo cat /etc/rancher/k3s/k3s.yaml" | \
    sed --expression 's/127\.0\.0\.1/{{host}}/' \
    > ~/.kube/config

bootstrap:
  #!/usr/bin/env bash
  set -euxo pipefail

  export GITHUB_TOKEN=$(op read "op://cluster-main/khjznpny7hv2gziibyiyit27fq/password")
  flux bootstrap github \
  --owner=nadavspi \
  --repository=kubernetes \
  --personal \
  --path=clusters/main

sops:
  op read "op://cluster-main/sops-age/age/private key" | \
       kubectl create secret generic sops-age \
       --namespace=flux-system \
       --from-file=age.agekey=/dev/stdin

