apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-oauth-client
  namespace: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  data:
  - secretKey: client-id
    remoteRef:
      key: tailscale-oauth-client
      property: client-id
  - secretKey: client-secret
    remoteRef:
      key: tailscale-oauth-client
      property: client-secret
