apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  url: https://kubernetes.github.io/ingress-nginx
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: infra-system
spec:
  chart:
    spec:
      chart: ingress-nginx # the actual name of the chart
      version: 4.9.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx # the name of the HelmRepository
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: ingress-nginx
  values:
    controller:
      ingressClassResource:
        default: true
      extraArgs:
        default-ssl-certificate: "infra-system/nadav-is-tls-prod"
