apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo # the actual name of the chart
      version: 6.5.4
      sourceRef:
        kind: HelmRepository
        name: podinfo # the name of the HelmRepository
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: podinfo
  values:
    service:
      type: LoadBalancer
