---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: infra-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: docker.io/1password/connect-api
              tag: &tag 1.7.2
            env:
              XDG_DATA_HOME: &configDir /config
              OP_HTTP_PORT: &apiPort 80
              OP_BUS_PORT: 11220
              OP_BUS_PEERS: localhost:11221
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: connect-server-credentials
                    key: 1password-credentials.json
          sync:
            image:
              repository: docker.io/1password/connect-sync
              tag: *tag
            env:
              XDG_DATA_HOME: *configDir
              OP_HTTP_PORT: &syncPort 8081
              OP_BUS_PORT: 11221
              OP_BUS_PEERS: localhost:11220
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: connect-server-credentials
                    key: 1password-credentials.json
    service:
      main:
        ports:
          http:
            port: *apiPort
    persistence:
      data:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: *configDir
            readOnly: false
