---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword
  namespace: infra-system
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect
      vaults:
        cluster: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
