---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: speedtest
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/librespeed
              tag: 5.3.0
            envFrom:
              - secretRef:
                  name: external-secret-test
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: speedtest.192.168.1.232.sslip.io
            paths:
              - path: /
                service:
                  name: main
                  port: http
    persistence:
      config:
        enabled: false
