apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: k8s-gateway
  namespace: flux-system
spec:
  interval: 5m
  url: https://ori-edge.github.io/k8s_gateway/
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: k8s-gateway
  annotations:
    metallb.universe.tf/loadBalancerIPs: "${K8S_DNS_IP}"
spec:
  chart:
    spec:
      chart: k8s-gateway # the actual name of the chart
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway # the name of the HelmRepository
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: k8s-gateway
  values:
    domain: "${SECRET_DOMAIN}"
    tls: 1
